# Generated by Django 2.1.3 on 2018-12-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20181203_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='postulacion',
        ),
    ]
