# Generated by Django 2.1.3 on 2018-12-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='postulado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
