# Generated by Django 2.1.3 on 2018-12-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elegir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('cargo', models.CharField(max_length=50)),
                ('coreo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='elegir',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Empleado'),
        ),
    ]
