# Generated by Django 2.1.3 on 2018-12-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='coreo',
            new_name='correo',
        ),
    ]
