# Generated by Django 2.1.3 on 2018-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20181203_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(max_length=15),
        ),
    ]
