# Generated by Django 2.1.3 on 2018-12-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20181203_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
